### ISSUE TITLE
There is no themes folder which waybar stylesheet uses

### ISSUE THREAD

**Issue by high-haseeb** [i4pg/dotfiles#3]
there is no ./waybar/themes/mocha.css which is required by the waybar style configuration. Instead ./waybar is an empty folder

**Comment by i4pg** [comment]
what's the full path of "waybar style configuration" file?

**Comment by im-calvin** [comment]
Modify the file in `latte.css` to change the path and then add the themes from here:

https://github.com/catppuccin/waybar
